define('registry', {
    'http://data.perseus.org/people/smith': 'perseus/smith',
    'http://en.wikipedia.org/wiki': 'wikipedia/page',
    'http://eol.org/pages': 'eol/eol',
    'http://finds.org.uk/database/artefacts': 'finds.org.uk/finds.org.uk',
    'http://fr.wikipedia.org/wiki': 'wikipedia/page',
    'http://lccn.loc.gov': 'loc/lccn',
    'http://nomisma.org/id': 'nomisma/nomisma',
    'http://numismatics.org/collection': 'numismatics.org/numismatics.org',
    'http://opencontext.org': 'opencontext/opencontext',
    'http://pleiades.stoa.org/places': 'pleiades/place',
    'http://wikipedia.org/wiki': 'wikipedia/page',
    'http://www.trismegistos.org/text': 'trismegistos/text',
    'http://www.papyri.info': 'papyri.info/text',
    'http://www.worldcat.org/oclc': 'worldcat/oclc',
});
